export const MAIN_HEADER_HEIGHT_D = 80;
export const MAIN_HEADER_HEIGHT_M = 56;

export const TV_TICKER_TAPE_WIDGET_HEIGHT = 46;

export const MAIN_HEADER_TOTAL_HEIGHT_D =
  MAIN_HEADER_HEIGHT_D + TV_TICKER_TAPE_WIDGET_HEIGHT;
export const MAIN_HEADER_TOTAL_HEIGHT_M =
  MAIN_HEADER_HEIGHT_M + TV_TICKER_TAPE_WIDGET_HEIGHT;

export const MAIN_FOOTER_HEIGHT_D = 64;
export const MAIN_FOOTER_HEIGHT_M = 106;
