export default {
  LANDING: "/",
  SIGNUP: "/signup",
  SIGNIN: "/signin",
  SIGNINLOADING: "/signin/loading",
  PROFILE: "/profile",
  DASHBOARD: "/dashboard",
  WATCHLISTS: "/watchlists",
  PORTFOLIOS: "/portfolios",
  PORTFOLIO: "/portfolio/:id",
  PORTFOLIOHOLDING: "/portfolio/:id/holding/:holdingId",
  INDICES: "/indices",
  STOCK: "/stock/:tickerSymbol",
  FALLBACK: "*",
};
