export default {
  LANDING: "/",
  SIGNUP: "/signup",
  SIGNIN: "/signin",
  OAUTHLOADING: "/signin/loading",
  PROFILE: "/settings/:tab",
  NOTIFICATIONS: "/notifications/:tab",
  DASHBOARD: "/dashboard",
  WATCHLISTS: "/watchlists",
  WATCHLIST: "/watchlists/:watchlistId",
  PORTFOLIOS: "/portfolios",
  PORTFOLIO: "/portfolio/:portfolioId",
  INDICES: "/indices/:tickerSymbol",
  STOCK: "/stock/:tickerSymbol",
  FALLBACK: "*",
};
